[package]
name = "zellij-favs"
version = "1.0.0"
authors = ["JoseMM2002 <jeolmmt@gmail.com>"]
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
owo-colors = "3"
zellij-tile = "0.43.1"
